import { Project } from "../../../../model/project/project";
import { PropertyGenerator } from "../../property/property-generator";

export class CMakeFileHeaderGenerator extends PropertyGenerator
{
	generate(_property: Project, _fileContent: string[]): void {
		_fileContent.push(`# File generated by the CMakeHelper vscode extension`)
	}	
}