export enum CMakeVariable
{
	PROJECT_VERSION = 'VERSION',
	PROJECT_INCLUDE_DIR = 'INCLUDE_DIR',
	PROJECT_SOURCE_DIR = 'SOURCE_DIR',
	PROJECT_SOURCE_FILES = 'SOURCE_FILES',
	INCLUDE_DIR_LIST = 'INCLUDE_DIR_LIST',
	LIBRARY_LIST = 'LIB_LIST',
	LIBRARY_INCLUDE_DIR_LIST = 'LIB_INCLUDE_DIR_LIST'
}